apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  label: redis
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-SC
  claimRef:
    name: redis-pvc
    namespace: { ? { .Values. namespace } }
