{{- range .Values.apps }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: autoscaler-for-{{ . }}
  namespace: {{ $.Values.Namespace }}  # Use $ to access the root context
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ . }}
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
{{- end }}
