apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  labels: 
    app: mongo
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.storageClassName }}
  local:  # ✅ Uses local storage while allowing node binding
    path: "/mnt/data/mongo"
  nodeAffinity:  # ✅ Ensures this PV is used only by a specific node
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minikube  # Replace with your actual node name
  claimRef:
    name: mongo-claim
    namespace: {{ .Values.namespace }}
