apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-claim
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: {{ .Values.storageClassName }}
  selector:
    matchLabels:
      app: mongo 