apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  labels: mongo
  app: mongo
  namespace: {{ .Values.namespace }}
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-SC
  claimRef:
    name: mongo-claim
    namespace: {{ .Values.namespace }}
