apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:  # ✅ Fixed labels (key-value format)
    app: mysql
  namespace: {{ .Values.namespace }}
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.storageClassName }}
  claimRef:
    name: mysql-claim
    namespace: {{ .Values.namespace }}
