apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    app: mysql
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.storageClassName }}
  hostPath:  
    path: "/mnt/data/mysql" 
    type: DirectoryOrCreate  
  claimRef:
    name: mysql-claim
    namespace: {{ .Values.namespace }}
