apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels: mysql
    app: mysql
  namespace: {{ .Values.namespace }}
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-SC
  claimRef:
    name: mysql-claim
    namespace: {{ .Values.namespace }}
