apiVersion: v1
kind: Service
metadata:
  name: payment
  labels:
    service: payment
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    service: payment
