# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: redis-claim
#   namespace: {{ .Values.namespace }}
# spec:
#   accessModes:
#     - ReadWriteOnce
#   volumeMode: Filesystem
#   resources:
#     requests:
#       storage: 1Gi
#   storageClassName: local-SC
#   selector:
#     matchLabels:
#       app: redis 