apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  labels:
    app: redis
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.storageClassName }}
  hostPath:  # ✅ Uses local storage while allowing node binding
    path: "/mnt/data/redis"
  # nodeAffinity:  # ✅ Ensures this PV is used only by a specific node
  #   required:
  #     nodeSelectorTerms:
  #       - matchExpressions:
  #           - key: kubernetes.io/hostname
  #             operator: In
  #             values:
  #               - minikube  # Replace with your actual node name
  claimRef:
    name: redis-claim
    namespace: {{ .Values.namespace }}
