apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  labels:
    app: redis
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.storageClassName }}  # ✅ Matches StatefulSet PVC
  hostPath:  # ✅ Uses local storage while allowing node binding
    path: /mnt/data/redis
  # Uncomment if you want to bind the PV to a specific node
  # nodeAffinity:  
  #   required:
  #     nodeSelectorTerms:
  #       - matchExpressions:
  #           - key: kubernetes.io/hostname
  #             operator: In
  #             values:
  #               - minikube  # Replace with your actual node name
