apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  labels: redis
  app: redis
  namespace: {{ .Values.namespace }}
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-SC
  claimRef:
    name: redis-claim
    namespace: {{ .Values.namespace }}
